resource_types:
- name: buildver-resource
  type: docker-image
  source:
    repository: lukaszz/buildver-resource

resources:
- name: build-develop-version
  type: buildver-resource
  source:
    bucket: axiom.config
    access_key: ((s3-key-id))
    secret_access_key: ((s3-access-key))
    file: qa/versions/api.txt
    driver: s3
    build_on: major

jobs:
- name: hello-world
  public: false
  plan:
  - get: build-develop-version
    trigger: true
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: echo
        args: ["Triggered!"]