#!/usr/bin/env python

import sys
import json

from os import path

def check(instream):
    input = json.load(instream)

    new_version = input["version"]["Version"].split(" ")[0].rstrip()

    full_path = path.join(sys.argv[1], 'version.txt')

    file = open(full_path, 'w') 
    file.write(new_version) 
    file.close() 

    payload = {
        "version" : {
            "Version" : u"%s" % (new_version)
        },
        "metadata" : [
            { "name": "Version", "value": new_version }
        ]
    }

    return payload

def main():
    print(json.dumps(check(sys.stdin)))

if __name__ == '__main__':
    main()
